// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYYRyfCr4Xvq8MWPHIkr29_qGJZuEl-ak',
    appId: '1:936036503134:web:98e4b57ab21bfb569eaecf',
    messagingSenderId: '936036503134',
    projectId: 'insta-clone-c3d55',
    authDomain: 'insta-clone-c3d55.firebaseapp.com',
    storageBucket: 'insta-clone-c3d55.appspot.com',
    measurementId: 'G-E3KC3PRXLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Ff1O_Z1JS3aArfiDaEoMyausUHJ5Rjw',
    appId: '1:936036503134:android:f2d70f77b9816d849eaecf',
    messagingSenderId: '936036503134',
    projectId: 'insta-clone-c3d55',
    storageBucket: 'insta-clone-c3d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsi0ebXettc0Jmdl4JB6LK4BZsqjHi9vI',
    appId: '1:936036503134:ios:ea52d5f80f1d94bb9eaecf',
    messagingSenderId: '936036503134',
    projectId: 'insta-clone-c3d55',
    storageBucket: 'insta-clone-c3d55.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsi0ebXettc0Jmdl4JB6LK4BZsqjHi9vI',
    appId: '1:936036503134:ios:6d3ebb6c71e502fa9eaecf',
    messagingSenderId: '936036503134',
    projectId: 'insta-clone-c3d55',
    storageBucket: 'insta-clone-c3d55.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
